##
# GitHub Actions workflow for commits into main
##

name: Stage-Deploy-Main-Workflow

on:
  workflow_dispatch:

jobs:
  start:
    runs-on:
        - self-hosted
        - Linux
        - X64
        - nomad
        - scaling
    steps:
      - name: "Clone"
        uses: actions/checkout@v4
